### ISSUE TITLE
Use async http client

### ISSUE THREAD

**Issue by 13h3r** [mukel/telegrambot4s#12]
Right now you are using synchronous http api which wrapped into `Future`. Let use truly async clients like spray-client, dispatch or so to provide real async communication

**Comment by mukel** [comment]
Indeed, it evolved (thanks to contributions) from being completely synchronous to what it is now. I'm planning to use Akka reactive streams for version 2. I choose Scalaj-http because it's really light and runs (easily) everywhere (notably Google Cloud). I even considered rolling out my own reactive stream implementation to avoid dependency-bloating. Akka reactive streams (with Akka http client) is the main candidate for the next version; but if you have a good argument on why use one of the libraries you mentioned let me know.

**Comment by 13h3r** [comment]
@mukel akka-http looks good for me

**Comment by mukel** [comment]
It's truly async now, take a lool
