### ISSUE TITLE
Commands order and their execution

### ISSUE THREAD

**Issue by joniybek** [mukel/telegrambot4s#26]
Hello @mukel 
It is great pleasure to read your code and use this project. I have some idea that I found useful and also I have implementation and I can contribute if you let me.
So when we give commands with on(some:String){function} they don't preserve order and if we have "registered"command twice in code it will be executed twice. What if we will make commands ordered, execute them once so that we will play around with commands that match from specific to more general one?
Cheers,
/Jakhongir

**Comment by mukel** [comment]
Indeed, the commands should be executed in order (of declaration). Right now it's still using a hash map from legacy versions (should be a ListBuffer). I'll gladly accept a PR.

Giving some sort of priority is difficult since it's hard to enforce it's proper use, after all commands are just a predicate with an attached action, it's left open for developers. It could be a good idea to relax access modifiers in Commands.scala (everything is private right now) to make it possible.

**Comment by mukel** [comment]
Fixed, commands are now processed in the order or declaration.
https://github.com/mukel/telegrambot4s/blob/master/src/main/scala/info/mukel/telegrambot4s/api/Actions.scala#L19
