### ISSUE TITLE
Code example from readme not compiling

### ISSUE THREAD

**Issue by bavadim** [mukel/telegrambot4s#34]
Code example from readme not compiling, version "info.mukel" %% "telegrambot4s" % "2.9.5".

error: not found: value onCommand
code:

```
object WebhookBot extends TelegramBot with Webhook with Commands {
  import info.mukel.telegrambot4s.Implicits._

  def token = "TOKEN"
  override val port = 443
  override val webhookUrl = "https://ed88ff73.ngrok.io"

  val rng = new Random(System.currentTimeMillis())
  onCommand("/coin") { implicit msg => reply(if (rng.nextBoolean()) "Head!" else "Tail!") }
  onCommand("/real") { implicit msg => reply(rng.nextDouble().toString) }
  onCommand("/die") { implicit msg => reply((rng.nextInt(6) + 1).toString) }
  onCommand("/dice") { implicit msg => reply((rng.nextInt(6) + 1) + " " + (rng.nextInt(6) + 1)) }
  onCommand("/random") { implicit msg =>
    withArgs {
      case Seq(Extractor.Int(n)) if n > 0 =>
        reply(rng.nextInt(n).toString)
      case _ =>
        reply("Invalid argumentヽ(ಠ_ಠ)ノ")
    }
  }
  onCommand("/choose") { implicit msg =>
    withArgs { args =>
      reply(if (args.isEmpty) "Empty list." else args(rng.nextInt(args.size)))
    }
  }
}
```

**Comment by laughedelic** [comment]
I think readme is just outdated. You can check examples in [src/test/scala/info/mukel/telegrambot4s/examples/](https://github.com/mukel/telegrambot4s/tree/master/src/test/scala/info/mukel/telegrambot4s/examples), I think all the code there compiles and works well.

**Comment by mukel** [comment]
Actually the README is up-to-date with a non-yet-released version (3.something).
It points to version **2.9.5**  as the latest stable release; before it pointed to a more recent SNAPSHOT version but people complained, so I reverted back to stable.

Please check the [version 2.9.5 tree](https://github.com/mukel/telegrambot4s/tree/v2.9.5) for the README + working examples for version 2.9.5.

If you want something fresh to work on, please use [this commit](https://jitpack.io/#info.mukel/telegrambot4s/b2d45341ef) from JitPack, it's pretty close the final release.

There's new features (and some breaking changes) since Bot API v3, the new onCommand one of them. 
This is not a toy project anymore, I'll change the workflow accordingly.
Keeping this open until it's fully resolved (most likely a new release).

**Comment by mukel** [comment]
Version 3.0.0 is out, please report any issues.
