### ISSUE TITLE
How to use Methods?

### ISSUE THREAD

**Issue by AlexanderShniperson** [mukel/telegrambot4s#39]
Hi
Examples cover only primitive commands like: onCommand, onCallbackQuery, etc
What about Methods, how to use them?
As example i want to `GetUserProfilePhotos` what should i do?

**Comment by mukel** [comment]
Methods are modeled using case classes to ease serialization, this allows to different strategies to call methods. E.g. retry on error, chained calls...
So indeed, constructing the case class have no effect,
to call a method use request(GetUserProfilePhoto(...)) which returns a future wrapping the method result.

Check TextToSpeechBot for a simple example. I'll try to add some design doc for it, since it's not obvious at first, but it is quite easy to use and works quite well.

**Comment by AlexanderShniperson** [comment]
ok, thank you
