### ISSUE TITLE
Download Audio File

### ISSUE THREAD

**Issue by VCGDEV** [mukel/telegrambot4s#56]
Sorry about this but I didn't find the way to extract an Audio file from server, I'm using this code:

`
 val fileRequest:GetFile = new GetFile(msg.audio.get.fileId) // whats the next step
`

Regards

**Comment by mukel** [comment]
GetFile is just a case class, you need to do request(GetFile(...)) to actually spawn the request.

Please check https://github.com/mukel/telegrambot4s/blob/refactor/examples/src/VoiceFileBot.scala it's an example for the upcoming library refactor.
It's a bot that receives voice files sent by users.
Note that GetFile will provide with a URL (filePath) that you can then use to request the actual file. You can download the file using any http client. I just used Akka-http because was already included.

I'll keep this open for a while, feel free to ping me here.

**Comment by VCGDEV** [comment]
Thanks, I already did my own implementation using your example :D regards (Y)
